### ISSUE TITLE
Password reset is not working

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/Pantry-for-Good#168]
When I submit a password reset request the server gets this error
```

Error: Invalid placeholder
    at bindPlaceholder (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/mail-generator.js:84:27)
    at span (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/mail-generator.js:55:7)
    at replace (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/html-transform.js:57:14)
    at reduceChildren (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/html-transform.js:33:23)
    at Array.reduce (native)
    at replace (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/html-transform.js:43:31)
    at reduceChildren (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/html-transform.js:33:23)
    at Array.reduce (native)
    at transform (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/html-transform.js:25:35)
    at transformHtml (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/html-transform.js:16:23)
    at transformBody (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/mail-generator.js:65:10)
    at /Users/okamoto/projects/Pantry-for-Good/server/lib/mail/mail-generator.js:28:16
    at Generator.next (<anonymous>)
    at step (/Users/okamoto/projects/Pantry-for-Good/server/lib/mail/mail-generator.js:41:191)
    at /Users/okamoto/projects/Pantry-for-Good/server/lib/mail/mail-generator.js:41:361
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by kenjiO** [comment]
I had to re-seed my database and then it fixed it
