### ISSUE TITLE
npm not working while deploying project locally

### ISSUE THREAD

**Issue by summitsingh** [freeCodeCamp/pantry-for-good#418]
I tried `npm install` but it has some errors. After npm install, I ran `npm run` dev but it is not working as expected and throwing some errors. Could someone please help me debug this issue, so my local environment starts working?

```Summits-MacBook-Pro:pantry-for-good summit$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> pantry-for-good@0.0.1 postinstall /Users/summit/pantry-for-good
> shx cp -n server/config/env/secrets-template.js server/config/env/secrets.js

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN css-loader@2.1.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-to-react@1.3.4 requires a peer of react@^16.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-bootstrap-autosuggest@0.5.0 requires a peer of react-bootstrap@^0.30.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-google-maps@9.4.5 requires a peer of @types/googlemaps@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-google-maps@9.4.5 requires a peer of @types/markerclustererplus@^2.1.29 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.7.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.4.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

audited 30499 packages in 10.728s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

```
Summits-MacBook-Pro:pantry-for-good summit$ npm run dev

> pantry-for-good@0.0.1 dev /Users/summit/pantry-for-good
> cross-env NODE_ENV=development gulp watch

assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/summit/pantry-for-good/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/summit/pantry-for-good/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/summit/pantry-for-good/gulpfile.js:16:6)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at execute (/Users/summit/pantry-for-good/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/Users/summit/pantry-for-good/node_modules/gulp/node_modules/gulp-cli/index.js:201:24)
    at Liftoff.execute (/Users/summit/pantry-for-good/node_modules/liftoff/index.js:201:12)
    at module.exports (/Users/summit/pantry-for-good/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/summit/pantry-for-good/node_modules/liftoff/index.js:191:5)
    at /Users/summit/pantry-for-good/node_modules/liftoff/index.js:149:9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pantry-for-good@0.0.1 dev: `cross-env NODE_ENV=development gulp watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pantry-for-good@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/summit/.npm/_logs/2019-05-27T18_15_52_381Z-debug.log```

**Comment by access0r** [comment]
I have the same. tried to manually update all. no progress.

**Comment by summitsingh** [comment]
@zephur thanks for the heads up! looks like no one is active on this project.

**Comment by dilipbobby** [comment]
npm install natives@1.1.6

add it in package.json It will help you to run the project

**Comment by andressalazar08** [comment]
I have the same issue, the solution gived by dilipbobby is not working, what can i do?, how can i fix it?, thanks in advance

**Comment by summitsingh** [comment]
This project is outdated.
